In [ ]:
import numpy as np
from numpy.testing import assert_allclose

# Part I. Construct a Householder reflection of a vector.

Given a vector $\mathbf{x}$, and a plane with a normal vector $\mathbf{u}$, the Householder transformation reflects $\mathbf{x}$ about the plane.

The matrix of the Householder transformation is

$$
\mathbf{H} = \mathbf{I} - 2 \mathbf{u} \mathbf{u}^T
$$

Given two equal-length vectors $\mathbf{x}$ and $\mathbf{y}$, a rotation which brings $\mathbf{x}$ to $\mathbf{y}$ is a Householder transform with

$$
\mathbf{u} = \frac{\mathbf{x} - \mathbf{y}}{\left|\mathbf{x} - \mathbf{y}\right|}
$$

Write a function which rotates a given vector, $\mathbf{x} = (x_1, \dots, x_n)$ into $\mathbf{y} = (\left|\mathbf{x}\right|, 0, \dots, 0)^T$ using a Householder transformation.

In [ ]:
from re import X

def householder(vec):
    n = len(vec)
    norm_vec = np.linalg.norm(vec)   
    v = np.copy(vec).astype(float)
    v[0] += np.sign(vec[0]) * norm_vec
    v /= np.linalg.norm(v)
    print(v.shape)
    H = np.eye(n) - 2 * np.outer(v, v)
    outvec = np.dot(H, vec)
    return outvec,H
v = np.array([1, 2, 1])
x,y=householder(v)


(3,)


Test your function using tests below:

In [ ]:
# Test I.1 (10% of the total grade).

v = np.array([1, 2, 3])
v1, h = householder(v)

assert_allclose(np.dot(h, v1), v)
assert_allclose(np.dot(h, v), v1)

(3,)


In [ ]:
# Test I.2 (10% of the total grade).

rndm = np.random.RandomState(1234)

vec = rndm.uniform(size=7)
v1, h = householder(vec)

assert_allclose(np.dot(h, v1), vec)

(7,)


# Part II. Compute the $\mathrm{QR}$ decomposition of a matrix.

Given a rectangular $m\times n$ matrix $\mathbf{A}$, construct a Householder reflector matrix $\mathbf{H}_1$ which transforms the first column of $\mathbf{A}$ (and call the result $\mathbf{A}^{(1)}$)

$$
\mathbf{H}_1 \mathbf{A} =%
\begin{pmatrix}
\times & \times & \times & \dots & \times \\
0      & \times & \times & \dots & \times \\
0      & \times & \times & \dots & \times \\
&& \dots&& \\
0      & \times & \times & \dots & \times \\
\end{pmatrix}%
\equiv \mathbf{A}^{(1)}\;.
$$

Now consider the lower-right submatrix of $\mathbf{A}^{(1)}$, and construct a Householder reflector which annihilates the second column of $\mathbf{A}$:

$$
\mathbf{H}_2 \mathbf{A}^{(1)} =%
\begin{pmatrix}
\times & \times & \times & \dots & \times \\
0      & \times & \times & \dots & \times \\
0      & 0      & \times & \dots & \times \\
&& \dots&& \\
0      & 0      & \times & \dots & \times \\
\end{pmatrix}%
\equiv \mathbf{A}^{(2)} \;.
$$

Repeating the process $n-1$ times, we obtain

$$
\mathbf{H}_{n-1} \cdots \mathbf{H}_2 \mathbf{H}_1 \mathbf{A} = \mathbf{R} \;,
$$

with $\mathbf{R}$ an upper triangular matrix. Since each $\mathbf{H}_k$ is orthogonal, so is their product. The inverse of an orthogonal matrix is orthogonal. Hence the process generates the $\mathrm{QR}$ decomposition of $\mathbf{A}$. 

$$
\mathbf{A} = (\mathbf{H}_{n-1} \cdots \mathbf{H}_2 \mathbf{H}_1)^{-1} \mathbf{R} \;,
$$
so 
$$
\mathbf{A} =  \mathbf{Q} \mathbf{R} \;,
$$
with
$$
\mathbf{Q} = (\mathbf{H}_{n-1} \cdots \mathbf{H}_2 \mathbf{H}_1)^{-1} =  \mathbf{H}_1^{-1}  \mathbf{H}_2^{-1}  \cdots \mathbf{H}_{n-1}^{-1} = \mathbf{H}_1^T  \mathbf{H}_2^T  \cdots \mathbf{H}_{n-1}^T 
$$
Since $\mathbf{H}_i$ is ortogonal
$$
\mathbf{H}_i\mathbf{H}_i^T = \mathbf{I}
$$
then
$$
\mathbf{H}^{-1} = \mathbf{H}^T 
$$
but also  $\mathbf{H}_i$ is symetric
$$
\mathbf{H}_i^T = \mathbf{H}_i
$$
so
$$
\mathbf{Q} = \mathbf{H}_1^{-1}  \mathbf{H}_2^{-1}  \cdots \mathbf{H}_{n-1}^{-1} = \mathbf{H}_1^T  \mathbf{H}_2^T  \cdots \mathbf{H}_{n-1}^T =  \mathbf{H}_1 \mathbf{H}_2  \cdots \mathbf{H}_{n-1}
$$


In [ ]:
from numpy.core.fromnumeric import size
np.set_printoptions(suppress=True)
def qr_decomp(a):

  def householder(vec,pos):
    if vec[pos]==0:
      n = len(vec)
      norm_vec = np.linalg.norm(vec)   
      v = np.copy(vec).astype(float)
      v[pos] -= 1 * norm_vec
      v /= np.linalg.norm(v)
      H = np.eye(n) - 2 * np.outer(v, v)
      outvec = np.dot(H, vec)
    else:
      n = len(vec)
      norm_vec = np.linalg.norm(vec)
      v = np.copy(vec).astype(float)
      v[pos] -= np.sign(vec[pos]) * norm_vec
      v /= np.linalg.norm(v)
      H = np.eye(n) - 2 * np.outer(v, v)
      outvec = np.dot(H, vec)
    return outvec,H
    
  fila,cola=a.shape
  _,H=householder(a[:,0],0)
  Ri=H@a
  Qi=H
  for i in range(1,cola-1):
    Vi=Ri.copy()
    Vi=np.transpose(Vi[:,i])
    Vi[i-1]=0
    _,Hi=householder(Vi,i)
    Ri=np.round(Hi@Ri,10)
    Qi=np.round(H@Hi,10)
  return Qi,Ri

In [ ]:
# Might want to turn this on for prettier printing: zeros instead of `1e-16` etc
np.set_printoptions(suppress=True)

In [ ]:
# Test II.1 (20% of the total grade)

rndm = np.random.RandomState(1234)
a = rndm.uniform(size=(5, 3))
q,r= qr_decomp(a)

# test that Q is indeed orthogonal
assert_allclose(np.dot(q, q.T), np.eye(5), atol=1e-10)

# test the decomposition itself
assert_allclose(np.dot(q, r), a)

Now compare your decompositions to the library function (which actually wraps the corresponding LAPACK functions)

La descomposición da muy similar, sin embargo, se evidencia un cambio en los signos de los componentes de la matriz y también la necesidad de usar cifras significativas suficientes para que según la tolerancia indicada se obtenga que el producto de Q y QT sea la matriz identidad, lo que comprueba ortogonalidad.

In [ ]:
from scipy.linalg import qr
rndm = np.random.RandomState(1234)
a = rndm.uniform(size=(5, 3))
qq, rr = qr(a)
assert_allclose(np.dot(qq, rr), a)

Check if your q and r agree with qq and rr. Explain.

La descomposición da muy similar, sin embargo, se evidencia un cambio en los signos de los componentes de la matriz y también la necesidad de usar cifras significativas suficientes para que según la tolerancia indicada se obtenga que el producto de Q y QT sea la matriz identidad, lo que comprueba ortogonalidad. El producto de las matrices Q y R siempre deben devolver la matriz original, en este caso, se cumple. 

In [ ]:
from scipy.linalg import qr
a = np.array([[4,3,1], [5,7,0], [9,9,3], [8,2,4], [9,3,1]])
q, r = qr_decomp(a)
qq, rr = qr(a)
print(q)
print(qq)
print(r)
print(rr)
print(a)
print(q@r)
print(qq@rr)

[[ 0.24479602  0.06723049  0.88467647  0.22294625  0.32124364]
 [ 0.30599503  0.58266423  0.18704939 -0.52598158 -0.50519831]
 [ 0.55079106  0.4964713  -0.40804552  0.44660369  0.29015419]
 [ 0.48959205 -0.47923271  0.03567661  0.36894623 -0.6270897 ]
 [ 0.55079106 -0.42406923 -0.12077289 -0.58143113  0.40514966]]
[[-0.24479602 -0.06723049  0.00981821 -0.41631113 -0.87300837]
 [-0.30599503 -0.58266423  0.33762629  0.64971343 -0.17535786]
 [-0.55079106 -0.4964713  -0.36457628 -0.41134781  0.38473703]
 [-0.48959205  0.47923271 -0.55563068  0.4547994  -0.1227505 ]
 [-0.55079106  0.42406923  0.66653641 -0.16884307  0.20979928]]
[[16.34013464 10.46503005  4.40632844]
 [-0.          6.51790964 -0.7843557 ]
 [-0.          0.         -0.31752655]
 [ 0.         -0.          2.45711113]
 [-0.         -0.         -0.91150293]]
[[-16.34013464 -10.46503005  -4.40632844]
 [  0.          -6.51790964   0.7843557 ]
 [  0.           0.          -2.63989693]
 [  0.           0.           0.        ]
 [  

Enter your explanation here (10% of the total grade, peer-graded)

A pesar que el uso de cifras significativas fue similar, se observa que las componentes en la matriz Q no son exactamente iguales, también se presentan signos cambiandos, esto puede ser a que el método de descomposición QR sea diferente con la librería de scipy, sin embargo, se observa que ambas descomposiciones son correctas porque el producto matricial de Q y R devuelven la matriz original y Q es una matriz ortogonal

# Part III. Avoid forming Householder matrices explicitly.

Note the special structure of the Householder matrices: A reflector $\mathbf{H}$ is completely specified by a reflection vector $\mathbf{u}$. Also note that the computational cost of applying a reflector to a matrix strongly depends on the order of operations:

$$
\left( \mathbf{u} \mathbf{u}^T \right) \mathbf{A}  \qquad \textrm{is } O(m^2 n)\;,
$$
while
$$
\mathbf{u} \left( \mathbf{u}^T \mathbf{A} \right) \qquad \textrm{is } O(mn)
$$

Thus, it seems to make sense to *avoid* forming the $\mathbf{H}$ matrices. Instead, one stores the reflection vectors, $\mathbf{u}$, themselves, and provides a way of multiplying an arbitrary matrix by $\mathbf{Q}^T$, e.g., as a standalone function (or a class).





Write a function which constructs the `QR` decomposition of a matrix *without ever forming the* $\mathbf{H}$ matrices, and returns the $\mathbf{R}$ matrix and reflection vectors. 

Write a second function, which uses reflection vectors to multiply a matrix with $\mathbf{Q}^T$. Make sure to include enough comments for a marker to follow your implementation, and add tests. 

(Peer-graded, 40% of the total grade)

$$
\mathbf{R} = \mathbf{H}_{n-1} \cdots \mathbf{H}_2 \mathbf{H}_1 \mathbf{A} 
$$
and 
$$
\mathbf{H}_i = \mathbf{I} - 2 \mathbf{u}_i \mathbf{u}_i^T
$$
so if
$$
\mathbf{R}_0 =  \mathbf{A}
$$
then 
$$
\mathbf{R}_1 = \mathbf{H}_1 \mathbf{R}_0= \ (\mathbf{I} - 2 \mathbf{u}_1 \mathbf{u}_1^T) \mathbf{R}_0 =  \mathbf{R}_0 -  2 \mathbf{u}_1 ( \mathbf{u}_1^T  \mathbf{R}_0)
$$
and
$$
\mathbf{R}_2 = \mathbf{H}_2 \mathbf{R}_1 = \ (\mathbf{I} - 2 \mathbf{u}_2 \mathbf{u}_2^T) \mathbf{R}_1 =  \mathbf{R}_1 -  2 \mathbf{u}_2 ( \mathbf{u}_2^T  \mathbf{R}_1)
$$
so on until
$$
\mathbf{R} = \mathbf{H}_n \mathbf{R}_{n-1} =  (\mathbf{I} - 2 \mathbf{u}_{n-1} \mathbf{u}_{n-1}^T) \mathbf{R}_{n-1} = \mathbf{R}_{n-1} -  2 \mathbf{u}_{n-1} ( \mathbf{u}_{n-1}^T  \mathbf{R}_{n-1})
$$

In [ ]:
def r_decomp(a):

    fila, cola = a.shape
    r = np.copy(a)
    vecs = []

#Ya que se usa la función range, el último valor evaluado será cola-1
    for i in range(cola):
        vec = r[i:, i]
        u = np.zeros(len(vec))
        u[0] = vec[0] + np.sign(vec[0]) * np.linalg.norm(vec)
        u[1:] = vec[1:]
        u /= np.linalg.norm(u)
        r[i:, i:] = r[i:, i:] - (2 * np.outer(u, np.dot(u, r[i:, i:])).astype(r.dtype))
        vecs.append(u)

    return r, vecs
#El output de esta función será el input para la descomposición Q, ya que se 
#realiza on los vectores de la transformación.

In [ ]:
from numpy.core.fromnumeric import size
np.set_printoptions(suppress=True)

$$
\mathbf{Q} =  \mathbf{H}_1 \mathbf{H}_2  \cdots \mathbf{H}_{n-1}
$$
and
$$
\mathbf{H}_i = \mathbf{I} - 2 \mathbf{u}_i \mathbf{u}_i^T
$$
so 
$$
\mathbf{Q} =  (\mathbf{I} - 2 \mathbf{u}_1 \mathbf{u}_1^T )( \mathbf{I} - 2 \mathbf{u}_2 \mathbf{u}_2^T)  \cdots (\mathbf{I} - 2 \mathbf{u}_{n-1} \mathbf{u}_{n-1}^T)
$$

In [ ]:

def q_decomp(vecs):

    m=len(vecs[0])
    n=len(vecs)
    Q = np.identity(m)
    
    for j in range(n-1, -1, -1):
        u = vecs[j]
        uT=np.dot(u, Q[j:, j:])
        Q[j:, j:] = Q[j:, j:] -(2 * np.outer(u,uT))
    return Q,Q.T    

In [ ]:
rndm = np.random.RandomState(1234)
a = rndm.uniform(size=(5, 3))
r, vecs = r_decomp(a)
q,qt = q_decomp(vecs)

# test that Q is indeed orthogonal
assert_allclose(np.dot(q, q.T), np.eye(5), atol=1e-10)

# test the decomposition itself
assert_allclose(np.dot(q, r), a)

In [ ]:
from scipy.linalg import qr
qq, rr = qr(a)

assert_allclose(np.dot(qq, rr), a)

In [ ]:
a = np.array([[4,3,1], [5,7,0], [9,9,3], [8,2,4], [9,3,1]])
R, vecs = r_decomp(a)
print("R\n ",R)
Q,QT = q_decomp(vecs)
print("Q\n",Q)
print("QT\n",QT)
print("QT@Q\n",QT@Q)
print("a\n",a)
print("Q@R\n",Q@R)

R
  [[-16  -9  -3]
 [  1  -7   0]
 [  1   1  -1]
 [  2   0   0]
 [  1  -1  -1]]
Q
 [[-0.24479602  0.37134325  0.35520807 -0.23155048 -0.78891742]
 [-0.30599503 -0.58291648  0.19741342  0.66749208 -0.28645712]
 [-0.55079106 -0.50988978 -0.20674184 -0.62723146  0.02191194]
 [-0.48959205  0.41573336 -0.69452363  0.3188391  -0.0586852 ]
 [-0.55079106  0.29915006  0.5565518   0.07590132  0.54002549]]
QT
 [[-0.24479602 -0.30599503 -0.55079106 -0.48959205 -0.55079106]
 [ 0.37134325 -0.58291648 -0.50988978  0.41573336  0.29915006]
 [ 0.35520807  0.19741342 -0.20674184 -0.69452363  0.5565518 ]
 [-0.23155048  0.66749208 -0.62723146  0.3188391   0.07590132]
 [-0.78891742 -0.28645712  0.02191194 -0.0586852   0.54002549]]
QT@Q
 [[ 1. -0. -0.  0.  0.]
 [-0.  1.  0.  0. -0.]
 [-0.  0.  1.  0. -0.]
 [ 0.  0.  0.  1.  0.]
 [ 0. -0. -0.  0.  1.]]
a
 [[4 3 1]
 [5 7 0]
 [9 9 3]
 [8 2 4]
 [9 3 1]]
Q@R
 [[ 3.39126933  0.74788693  1.16809743]
 [ 5.55894447  7.31824118  1.00702879]
 [ 6.86347428  8.29769415  