In [ ]:
 pip install -U fortran-magic

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 52.3 MB/s eta 0:00:00


In [ ]:
%matplotlib inline
%load_ext fortranmagic

import sys; sys.path.append('..')
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

mpl.rc('figure', figsize=(12, 7))

ran_the_first_cell = True

#pd.to_datetime sirve para pasar strings de fechas desde objetos a datetime
#Permite hacer operaciones en DF
jan2017 = pd.to_datetime(['2017-01-03 00:00:00+00:00',
 '2017-01-04 00:00:00+00:00',
 '2017-01-05 00:00:00+00:00',
 '2017-01-06 00:00:00+00:00',
 '2017-01-09 00:00:00+00:00',
 '2017-01-10 00:00:00+00:00',
 '2017-01-11 00:00:00+00:00',
 '2017-01-12 00:00:00+00:00',
 '2017-01-13 00:00:00+00:00',
 '2017-01-17 00:00:00+00:00',
 '2017-01-18 00:00:00+00:00',
 '2017-01-19 00:00:00+00:00',
 '2017-01-20 00:00:00+00:00',
 '2017-01-23 00:00:00+00:00',
 '2017-01-24 00:00:00+00:00',
 '2017-01-25 00:00:00+00:00',
 '2017-01-26 00:00:00+00:00',
 '2017-01-27 00:00:00+00:00',
 '2017-01-30 00:00:00+00:00',
 '2017-01-31 00:00:00+00:00',
 '2017-02-01 00:00:00+00:00'])

calendar = jan2017.values.astype('datetime64[D]')
#Te entrega valores organizados de fechas por días 
print(calendar)

event_dates = pd.to_datetime(['2017-01-06 00:00:00+00:00', 
                             '2017-01-07 00:00:00+00:00', 
                             '2017-01-08 00:00:00+00:00']).values.astype('datetime64[D]')

print(event_dates)
event_values = np.array([10, 15, 20])

print(event_values)

/usr/local/lib/python3.8/dist-packages/fortranmagic.py:147: UserWarning: get_ipython_cache_dir has moved to the IPython.paths module since IPython 4.0.
  self._lib_dir = os.path.join(get_ipython_cache_dir(), 'fortran')


['2017-01-03' '2017-01-04' '2017-01-05' '2017-01-06' '2017-01-09'
 '2017-01-10' '2017-01-11' '2017-01-12' '2017-01-13' '2017-01-17'
 '2017-01-18' '2017-01-19' '2017-01-20' '2017-01-23' '2017-01-24'
 '2017-01-25' '2017-01-26' '2017-01-27' '2017-01-30' '2017-01-31'
 '2017-02-01']
['2017-01-06' '2017-01-07' '2017-01-08']
[10 15 20]


<center>
  <h1>The PyData Toolbox</h1>
  <h3>Scott Sanderson (Twitter: @scottbsanderson, GitHub: ssanderson)</h3>
  <h3><a href="https://github.com/ssanderson/pydata-toolbox">https://github.com/ssanderson/pydata-toolbox</a></h3>
</center>

# About Me:

<img src="https://raw.githubusercontent.com/ssanderson/pydata-toolbox/master/notebooks/images/me.jpg" alt="Drawing" style="width: 300px;"/>

- Senior Engineer at [Quantopian](www.quantopian.com)
- Background in Mathematics and Philosophy
- **Twitter:** [@scottbsanderson](https://twitter.com/scottbsanderson)
- **GitHub:** [ssanderson](github.com/ssanderson)

## Outline

- Built-in Data Structures
- Numpy `array`
- Pandas `Series`/`DataFrame`
- Plotting and "Real-World" Analyses

# Data Structures

> Rule 5. Data dominates. If you've chosen the right data structures and organized things well, the algorithms
will almost always be self-evident. Data structures, not algorithms, are central to programming.

- *Notes on Programming in C*, by Rob Pike.

# Lists

In [ ]:
assert ran_the_first_cell, "Oh noes!"

In [ ]:
l = [1, 'two', 3.0, 4, 5.0, "six"]
l

[1, 'two', 3.0, 4, 5.0, 'six']

In [ ]:
# Lists can be indexed like C-style arrays.
first = l[0]
second = l[1]
print("first:", first)
print("second:", second)

first: 1
second: two


In [ ]:
# Negative indexing gives elements relative to the end of the list.
last = l[-1]
penultimate = l[-2]
print("last:", last)
print("second to last:", penultimate)

last: six
second to last: 5.0


In [ ]:
# Lists can also be sliced, which makes a copy of elements between 
# start (inclusive) and stop (exclusive)
sublist = l[1:3]
sublist

['two', 3.0]

In [ ]:
# l[:N] is equivalent to l[0:N].
first_three = l[:3]
first_three

[1, 'two', 3.0]

In [ ]:
# l[3:] is equivalent to l[3:len(l)].
after_three = l[3:]
after_three

[4, 5.0, 'six']

In [ ]:
# There's also a third parameter, "step", which gets every Nth element.
l = ['a', 'b', 'c', 'd', 'e', 'f', 'g','h']
l[1:7:2]

['b', 'd', 'f']

In [ ]:
# This is a cute way to reverse a list.
l[::-1]

['h', 'g', 'f', 'e', 'd', 'c', 'b', 'a']

In [ ]:
# Lists can be grown efficiently (in O(1) amortized time).
l = [1, 2, 3, 4, 5]
print("Before:", l)
l.append('six')
print("After:", l)

Before: [1, 2, 3, 4, 5]
After: [1, 2, 3, 4, 5, 'six']


In [ ]:
# Comprehensions let us perform elementwise computations.
l = [1, 2, 3, 4, 5]
[x * 2 for x in l]

[2, 4, 6, 8, 10]

## Review: Python Lists

- Zero-indexed sequence of arbitrary Python values.
- Slicing syntax: `l[start:stop:step]` copies elements at regular intervals from `start` to `stop`.
- Efficient (`O(1)`) appends and removes from end.
- Comprehension syntax: `[f(x) for x in l if cond(x)]`.

# Dictionaries

In [ ]:
# Dictionaries are key-value mappings.
philosophers = {'David': 'Hume', 'Immanuel': 'Kant', 'Bertrand': 'Russell'}
philosophers

{'David': 'Hume', 'Immanuel': 'Kant', 'Bertrand': 'Russell'}

In [ ]:
# Like lists, dictionaries are size-mutable.
philosophers['Ludwig'] = 'Wittgenstein'
philosophers

{'David': 'Hume',
 'Immanuel': 'Kant',
 'Bertrand': 'Russell',
 'Ludwig': 'Wittgenstein'}

In [ ]:
del philosophers['David']
philosophers

{'Immanuel': 'Kant', 'Bertrand': 'Russell', 'Ludwig': 'Wittgenstein'}

In [ ]:
# No slicing.
philosophers['Bertrand':'Immanuel']

TypeError: ignored

## Review: Python Dictionaries

- Unordered key-value mapping from (almost) arbitrary keys to arbitrary values.
- Efficient (`O(1)`) lookup, insertion, and deletion.
- No slicing (would require a notion of order).

<center><img src="https://raw.githubusercontent.com/ssanderson/pydata-toolbox/master/notebooks/images/pacino.gif" alt="Drawing" style="width: 100%;"/></center>


In [ ]:
# Suppose we have some matrices...
a = [[1, 2, 3],
     [2, 3, 4],
     [5, 6, 7],
     [1, 1, 1]]

b = [[1, 2, 3, 4],
     [2, 3, 4, 5]]

In [ ]:
def matmul(A, B):
    """Multiply matrix A by matrix B."""
    rows_out = len(A)
    cols_out = len(B[0])
    out = [[0 for col in range(cols_out)] for row in range(rows_out)]
    
    for i in range(rows_out):
        for j in range(cols_out):
            for k in range(len(B)):
                out[i][j] += A[i][k] * B[k][j]
    return out

<center><img src="https://raw.githubusercontent.com/ssanderson/pydata-toolbox/master/notebooks/images/gross.gif" alt="Drawing" style="width: 50%;"/></center>


In [ ]:
%%time

matmul(a, b)

CPU times: user 79 µs, sys: 4 µs, total: 83 µs
Wall time: 109 µs


[[5, 8, 11, 14], [8, 13, 18, 23], [17, 28, 39, 50], [3, 5, 7, 9]]

**My own example 0 - cpu info**

In [ ]:
!cat /proc/cpuinfo

processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 79
model name	: Intel(R) Xeon(R) CPU @ 2.20GHz
stepping	: 0
microcode	: 0xffffffff
cpu MHz		: 2200.228
cache size	: 56320 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt arat md_clear arch_capabilities
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa mmio_stale_data retbleed
bogomips	: 4400.45
clflush size	: 64
cache_alignment	: 64
addres

**My own example 1 - Changing in matmul(A, B) Python len(B) (# of rows of B) for len(A[0]) (# of columns of A)**

In [ ]:
def matmul(A, B):
    #len(A) entrega la dimensión de filas
    rows_out = len(A)
    #len(B[0]) entrega la dimensión de columnas
    cols_out = len(B[0])
    #Esto define la matriz de ceros
    out = [[0 for col in range(cols_out)] for row in range(rows_out)]
    #len(B) indica la dimensión en filas
    for i in range(rows_out):
        for j in range(cols_out):
            for k in range(len(B)):
                out[i][j] += A[i][k] * B[k][j]
    return out

**My own example 2 - Verifiying error with in matmul(A, B) Python with the original matrices when changing len(B) (# of rows of B) for len(A[0]) (# of colums of A)**

In [ ]:
#Cambiar las condiciones de dimensiones de la matriz
def matmul(A, B):
    #len(A) entrega la dimensión de filas
    rows_out = len(A)
    #len(B[0]) entrega la dimensión de columnas
    cols_out = len(B[0])
    #Esto define la matriz de ceros
    out = [[0 for col in range(cols_out)] for row in range(rows_out)]
    #len(B) indica la dimensión en filas
    #SE CAMBIA len(B) (dimensión de filas en B) por len(A[0]) (dimensión de columnas en A)
    for i in range(rows_out):
        for j in range(cols_out):
            for k in range(len(A[0])):
                out[i][j] += A[i][k] * B[k][j]
    return out
#Se obtiene error porque index queda fuera del rango
matmul(a,b)

IndexError: ignored

**My own example 3 - Chekcing the mtarix multiplication compatibility condition  len(A[0]) == len(B)**

In [ ]:
#Comprobar si la condición es len(A[0])==len(B)
#Es decir, dim columnas A = dim filas B

def matmul(A, B):
    #len(A) entrega la dimensión de filas
    rows_out = len(A)
    #len(B[0]) entrega la dimensión de columnas
    cols_out = len(B[0])
    #Esto define la matriz de ceros
    out = [[0 for col in range(cols_out)] for row in range(rows_out)]
    #len(B) indica la dimensión en filas
    for i in range(rows_out):
        for j in range(cols_out):
            for k in range(len(A[0])):
                out[i][j] += A[i][k] * B[k][j]
    return out

#Solo funciona si la dimensión de columnas de la primera es igual a dimensión columnas de la segunda
import numpy as np

A=np.array([[1,0,0],[0,0,1],[0,1,0]])

B=np.array([[1,2,3],[4,5,6],[7,8,9]])

matmul(A,B)

[[1, 2, 3], [7, 8, 9], [4, 5, 6]]

**My own example 4 -  Verifiying error with in matmul(A, B) Python when checking the mtarix multiplication compatibility condition  len(A[0]) == len(B)**

In [ ]:
#Comprobar si la condición es len(A[0])==len(B)
#Es decir, dim columnas A = dim filas B

def matmul(A, B):
    #len(A) entrega la dimensión de filas
    rows_out = len(A)
    #len(B[0]) entrega la dimensión de columnas
    cols_out = len(B[0])
    #Esto define la matriz de ceros
    out = [[0 for col in range(cols_out)] for row in range(rows_out)]
    #len(B) indica la dimensión en filas
    for i in range(rows_out):
        for j in range(cols_out):
            for k in range(len(A[0])):
                out[i][j] += A[i][k] * B[k][j]
    return out

#Solo funciona si la dimensión de columnas de la primera es igual a dimensión columnas de la segunda

a = [[1, 2, 3],
     [2, 3, 4],
     [5, 6, 7],
     [1, 1, 1]]

b = [[1, 2, 3, 4],
     [2, 3, 4, 5]]

matmul(a,b)

IndexError: ignored

**My own example 5 - Deifining A and B that are compatible for multiplcation**

In [ ]:
A=np.array([[1,0,0],[0,0,1],[0,1,0]])

B=np.array([[1,2,3],[4,5,6],[7,8,9]])

matmul(A,B)

[[1, 2, 3], [7, 8, 9], [4, 5, 6]]

**My own example 6 - Runinng the correct Python matrix multiplication code with the matrices with dimensions compatible for multiplication.**

In [ ]:
import random

In [ ]:
random.normalvariate(0,1)

1.397950764525187

In [ ]:
import random
def random_matrix(m, n):
    out = []
    for row in range(m):
        out.append([random.random() for col in range(n)])
    return out

randm = random_matrix(2, 3)
randm

[[0.07451135984224921, 0.25290979422732485, 0.6971142121138622],
 [0.08889938140232068, 0.548345123168495, 0.28022394382792426]]

**My own example 7 - Running 10 times matmul(randa, randb) with randa and randb a randon matrices of 600 x 100 and 100 x 600 and calulating the average execution time**

In [ ]:
from numpy.core.fromnumeric import mean
import time
randa=random_matrix(600,100)
randb=random_matrix(100,600)
list1=[]
def tiempo(intentos,randa,randb):
  for i in range(intentos):
    inicio=time.time()
    matmul(randa,randb)
    final=time.time()
    list1.append(final-inicio)
    prom_py=np.mean(list1)
  return prom_py
prom_py=tiempo(10,randa,randb)
print("El tiempo promedio por multipicación es {0}".format(prom_py))

El tiempo promedio por multipicación es 11.22497317790985


**My own example 8 - Creating the average execution time data frame and adding Python's average execution time**

In [ ]:
#Crear un dataframe para almacenar los tiempos de ejecución por cada lenguaje
import pandas as pd
def app_df(df,leng,prom):
  nuevo_df=pd.DataFrame({"Lenguaje":[leng],"Prom. Tiempo":[prom]})
  return df.append(nuevo_df)

#Crear el dataframe vacío para empezar a almacenar info.
df=pd.DataFrame({"Lenguaje":[],"Prom. Tiempo":[]})
df=app_df(df,"Python",prom_py)
df

Lenguaje  Prom. Tiempo
0   Python     11.224973

**My own example 9 - Running 10 times randa and randb mutiplicaction as NumPy arrays  adding NumPy's average execution time**

In [ ]:
#Convertir las matrices a np.array
randa_np=np.array(randa)
randb_np=np.array(randb)
list1=[]
def tiempo_np(intentos,randa_np,randb_np):
  for i in range(intentos):
    inicio=time.time()
    np.matmul(randa_np,randb_np)
    final=time.time()
    list1.append(final-inicio)
    prom_np=np.mean(list1)
  return prom_np
prom_np=tiempo_np(10,randa_np,randb_np)
print("El tiempo promedio por multipicación es {0}".format(prom_np))
#Se iguala al DF antiguo para que se reescriba
df=app_df(df,"NumPy",prom_np)
df

El tiempo promedio por multipicación es 0.003169131278991699


Lenguaje  Prom. Tiempo
0   Python     11.224973
0    NumPy      0.003169

In [ ]:
%%time
randa = random_matrix(600, 100)
randb = random_matrix(100, 600)
x = matmul(randa, randb)

CPU times: user 10.8 s, sys: 28.1 ms, total: 10.8 s
Wall time: 10.9 s


In [ ]:
# Maybe that's not that bad?  Let's try a simpler case.
def python_dot_product(xs, ys):
    return sum(x * y for x, y in zip(xs, ys))

In [ ]:
%%fortran
subroutine fortran_dot_product(xs, ys, result)
    double precision, intent(in) :: xs(:)
    double precision, intent(in) :: ys(:)
    double precision, intent(out) :: result
    
    result = sum(xs * ys)
end

In [ ]:
list_data = [float(i) for i in range(100000)]
array_data = np.array(list_data)

In [ ]:
%%time
python_dot_product(list_data, list_data)

CPU times: user 43.5 ms, sys: 0 ns, total: 43.5 ms
Wall time: 46.2 ms


333328333350000.0

In [ ]:
%%time
fortran_dot_product(array_data, array_data)

CPU times: user 212 µs, sys: 1 µs, total: 213 µs
Wall time: 221 µs


333328333350000.0

<center><img src="https://raw.githubusercontent.com/ssanderson/pydata-toolbox/master/notebooks/images/sloth.gif" alt="Drawing" style="width: 1080px;"/></center>


**My own example 10 - Deifining A (2x2)  and B (2x2)**

In [ ]:
Af = np.array([[10.0, 20.0],[30.0, 40.0]])

Bf = np.array([[15.0, 25.0],[35.0, 45.0]])

**My own example 11 - Defining Fortran subroutine matmul(A,B) for 2x2 matrices**

In [ ]:
%%fortran
subroutine fortran_matmul(m1, m2, R)
     double precision, intent(in) :: m1(2,2)
     double precision, intent(in) :: m2(2,2)
     double precision, intent(out) :: R(2,2)
  
    do i=1,2
      do j=1,2
        do k=1,2
          R(i,j) = R(i,j) + m1(i,k) * m2(k,j)
        end do
      end do
    end do
end

**My own example 12 -Run Fortran subroutine matmul(A,B) with a and b 2x2 matrices**

In [ ]:
%%time
fortran_matmul(Af, Bf)

CPU times: user 74 µs, sys: 2 µs, total: 76 µs
Wall time: 84.2 µs


array([[ 850., 1150.],
       [1850., 2550.]])

**My own example 13 - Defining Fortran subroutine matmul(A,B) for 600x100 and 100x600 matrices**

In [ ]:
%%fortran
subroutine fortran_matmul_600(m1, m2, R)
     real, intent(in) :: m1(600,100)
     real, intent(in) :: m2(100,600)
     real, intent(out) :: R(600,600)
  
    do i=1,600
      do j=1,600
        do k=1,100
          R(i,j) = R(i,j) + m1(i,k) * m2(k,j)
        end do
      end do
    end do
end

**My own example 14 -Run Fortran subroutine matmul(A,B) with 600x100 and 100x600 matrices**

In [ ]:
randma =np.array( random_matrix(600, 100))
randmb =np.array( random_matrix(100, 600))
fortran_matmul_600(randma, randmb)

array([[28.014917, 27.93194 , 24.889154, ..., 25.619503, 25.390574,
        26.909178],
       [26.76374 , 25.109028, 23.517082, ..., 24.06188 , 25.630026,
        24.310131],
       [27.858006, 28.539358, 24.477564, ..., 27.876642, 26.407022,
        26.498165],
       ...,
       [28.245008, 29.365536, 24.238075, ..., 26.993519, 24.168829,
        25.845736],
       [25.354465, 24.740648, 20.798649, ..., 24.346638, 23.305387,
        20.97449 ],
       [26.184404, 24.512026, 22.996223, ..., 25.429703, 23.217028,
        24.775139]], dtype=float32)

**My own example 15 - Running 10 times the  Fortran subroutine matmul(A,B) with 600x100 and 100x600 matrices and adding Fortran magic average execution time to the data frame**

In [ ]:
from numpy.core.fromnumeric import mean
import time
randma =np.array( random_matrix(600, 100))
randmb =np.array( random_matrix(100, 600))
list1=[]
def tiempo(intentos,randa,randb):
  for i in range(intentos):
    inicio=time.time()
    fortran_matmul_600(randma, randmb)
    final=time.time()
    list1.append(final-inicio)
  return list1
tiempo(10,randma,randmb)
print("El tiempo promedio por multipicación es {0}".format(np.mean(list1)))
print((list1))
prom_fm=np.mean(list1)
df=app_df(df,"Fortran Magic",prom_fm)
df

El tiempo promedio por multipicación es 0.05829906463623047
[0.05803990364074707, 0.06075787544250488, 0.05533409118652344, 0.056525468826293945, 0.062407732009887695, 0.06627583503723145, 0.05709576606750488, 0.05412554740905762, 0.0543217658996582, 0.05810666084289551]


Lenguaje  Prom. Tiempo
0         Python     11.224973
0          NumPy      0.003169
0  Fortran Magic      0.058299

**My own example 16 - Creating a  Fortran program that mutiplies 10 times A(600x100) and  B (100x600) matrices**

In [ ]:
!apt-get install gfortran
!gfortran --version

Reading package lists... Done
Building dependency tree       
Reading state information... Done
gfortran is already the newest version (4:9.3.0-1ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 22 not upgraded.
GNU Fortran (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.



In [ ]:

%%writefile matrix_multiplication.f90
program matrix_multiplication
  implicit none
  
  integer, parameter :: n = 600, m = 100, p = 600
  integer :: i, j, k, iter
  
  real, dimension(n,m) :: a
  real, dimension(m,p) :: b
  real, dimension(n,p) :: c
  
  call random_seed()
  call random_number(a)
  call random_number(b)

  do iter=1,10
     do i=1,n
        do j=1,p
           c(i,j) = 0.0
           do k=1,m
              c(i,j) = c(i,j) + a(i,k) * b(k,j)
           end do
        end do
     end do
     write(*,*) 'Iteration', iter, 'completed'
  end do
  

end program matrix_multiplication

Writing matrix_multiplication.f90


**My own example 17 - Running the Fortran program that mutiplies 10 times A(600x100) and  B (100x600) matrices**

In [ ]:
!gfortran -o matrix_multiplication matrix_multiplication.f90
!./matrix_multiplication

 Iteration           1 completed
 Iteration           2 completed
 Iteration           3 completed
 Iteration           4 completed
 Iteration           5 completed
 Iteration           6 completed
 Iteration           7 completed
 Iteration           8 completed
 Iteration           9 completed
 Iteration          10 completed


**My own example 18 - Adding Fortran average execution time to the data frame**

In [ ]:

randma =np.array( random_matrix(600, 100))
randmb =np.array( random_matrix(100, 600))
list2=[]
def tiempo(intentos,randa,randb):
  for i in range(1):
    inicio=time.time()
    !gfortran -o matrix_multiplication matrix_multiplication.f90
    !./matrix_multiplication
    
    final=time.time()
    list2.append(final-inicio)
  return list2
tiempo(10,randma,randmb)
print("El tiempo promedio por multipicación es {0}".format(np.mean(list2)/10))
prom_f=np.mean(list2)/10
df=app_df(df,"Fortran",prom_f)
df


 Iteration           1 completed
 Iteration           2 completed
 Iteration           3 completed
 Iteration           4 completed
 Iteration           5 completed
 Iteration           6 completed
 Iteration           7 completed
 Iteration           8 completed
 Iteration           9 completed
 Iteration          10 completed
El tiempo promedio por multipicación es 0.24531519412994385


Lenguaje  Prom. Tiempo
0         Python     11.224973
0          NumPy      0.003169
0  Fortran Magic      0.058299
0        Fortran      0.245315

**My own example 19 - Creating a c program that mutiplies 10 times A(600x100) and  B (100x600) matrices**

In [ ]:
%%writefile matrix_multiplication.c
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

#define N 600
#define M 100
#define P 600

void matrix_multiplication(float A[N][M], float B[M][P], float C[N][P]) {
    int i, j, k;
    for (i = 0; i < N; i++) {
        for (j = 0; j < P; j++) {
            C[i][j] = 0;
            for (k = 0; k < M; k++) {
                C[i][j] += A[i][k] * B[k][j];
            }
        }
    }
}

int main() {
    float A[N][M], B[M][P], C[N][P];
    int i, j, k, iter;

    srand(time(NULL));
    for (i = 0; i < N; i++) {
        for (j = 0; j < M; j++) {
            A[i][j] = (float)rand() / (float)RAND_MAX;
        }
    }
    for (i = 0; i < M; i++) {
        for (j = 0; j < P; j++) {
            B[i][j] = (float)rand() / (float)RAND_MAX;
        }
    }

    for (iter = 0; iter < 10; iter++) {
        matrix_multiplication(A, B, C);
        printf("%d completado\n", iter+1);
    }

    return 0;
}

Writing matrix_multiplication.c


**My own example 20 - Running the c program that mutiplies 10 times A(600x100) and  B (100x600) matrices**

In [ ]:
!gcc matrix_multiplication.c -o matrix_multiplication
!./matrix_multiplication

1 completado
2 completado
3 completado
4 completado
5 completado
6 completado
7 completado
8 completado
9 completado
10 completado


**My own example 21 - Adding c average execution time to the data frame**

In [ ]:

list3=[]
def tiempo():
  for i in range(1):
    inicio=time.time()

    !gcc matrix_multiplication.c -o matrix_multiplication
    !./matrix_multiplication
    
    final=time.time()

    list3.append(final-inicio)

  return list3
tiempo()
print("El tiempo promedio por multipicación es {0}".format(np.mean(list3)/10))
prom_c=np.mean(list3)/10
df=app_df(df,"c",prom_c)
df

1 completado
2 completado
3 completado
4 completado
5 completado
6 completado
7 completado
8 completado
9 completado
10 completado
El tiempo promedio por multipicación es 0.20493245124816895


Lenguaje  Prom. Tiempo
0         Python     11.224973
0          NumPy      0.003169
0  Fortran Magic      0.058299
0        Fortran      0.245315
0              c      0.204932

**My own example 22 - Creating a C++ program that mutiplies 10 times A(600x100) and  B (100x600) matrices**

In [ ]:
%%writefile matsam.cpp
  #include <stdio.h>
  #include <stdlib.h>
  #include <time.h>
  #include <iostream>

  using namespace std;

  void fillMatrix(int **matriz, int filas, int columnas);
  void matsam(int **matrizA, int **matrizB, int **result, int filas, int columnas);
  double multAverage(int **matrizA, int **matrizB, int **result, int filas, int columnas, int rep);

  int main(void) {
    FILE *fileAvr;
    int filas = 600;
    int columnas = 100;

    int **pmatrizA;
    int **pmatrizB;
    int **presult;
    unsigned int rep = 10;
    double average = 0.0;

    //matrix pointers
    pmatrizA = (int **) malloc(filas * sizeof(int *)); 
    for(int a = 0; a < filas; a++){
      pmatrizA[a] = (int *) malloc(columnas * sizeof(int)); 
    }

    pmatrizB = (int **) malloc(columnas * sizeof(int *));
    for(int a = 0; a < columnas; a++){
      pmatrizB[a] = (int *) malloc(filas * sizeof(int));
    }

    presult = (int **) malloc(filas * sizeof(int *));
    for(int a = 0; a < filas; a++){
      presult[a] = (int *) malloc(filas * sizeof(int));
    }

  
    fillMatrix(pmatrizA, filas, columnas);
    fillMatrix(pmatrizB, columnas, filas);

    
    average = multAverage(pmatrizA, pmatrizB, presult, filas, columnas, rep);
    printf("Promedio en C++: %f segundos\n",average);

   
    fileAvr = fopen("c_mas_average.txt", "w");
    fprintf(fileAvr,"%f",average);
    fclose(fileAvr);

    return 0;
  }

  void fillMatrix(int **matriz, int filas, int columnas){
    for(int a=0; a<filas; a++){
      for(int b=0; b<columnas; b++){
        matriz[a][b] = rand();
      }
    }
    return;
  }

  double multAverage(int **matrizA, int **matrizB, int **result, int filas, int columnas, int rep){
    clock_t start, end;
    double average = 0.0;
    double execution = 0.0;

    for(int a=0; a<rep; a++){
      start = clock();
      matsam(matrizA, matrizB, result, filas, columnas);
      end = clock();
      execution = ((double)(end - start))/CLOCKS_PER_SEC;
      average += execution;
      printf("Repetición %d -> %f segundos\n",a+1, execution);
    }
    return average/((double) rep);
  }

  void matsam(int **matrizA, int **matrizB, int **result, int filas, int columnas){


    for(int a=0; a<filas; a++){
      for(int b=0; b<filas; b++){
        for(int f=0; f<columnas; f++){
          result[a][b] += matrizA[a][f] * matrizB[f][b];
        }
      }
    }
    return;
  }

Writing matsam.cpp


**My own example 23 - Running the C++ program that mutiplies 10 times A(600x100) and  B (100x600) matrices**

In [ ]:
!g++ matsam.cpp -o matsam
!./matsam

Repetición 1 -> 0.368877 segundos
Repetición 2 -> 0.363905 segundos
Repetición 3 -> 0.367324 segundos
Repetición 4 -> 0.369482 segundos
Repetición 5 -> 0.367843 segundos
Repetición 6 -> 0.369504 segundos
Repetición 7 -> 0.250346 segundos
Repetición 8 -> 0.208750 segundos
Repetición 9 -> 0.209527 segundos
Repetición 10 -> 0.212215 segundos
Promedio en C++: 0.308777 segundos


**My own example 24 - Adding C++ average execution time to the data frame**

In [ ]:
c_mas_file = open('c_mas_average.txt','r')
promedio_c_mas = float(c_mas_file.readline())

df=app_df(df,"C++",promedio_c_mas)
df

Lenguaje  Prom. Tiempo
0         Python     11.224973
0          NumPy      0.003169
0  Fortran Magic      0.058299
0        Fortran      0.245315
0              c      0.204932
0            C++      0.308777

**My own example 25 - Creating a Java program that mutiplies 10 times A(600x100) and  B (100x600) matrices**

In [ ]:
%%writefile MatMul.java

  import java.util.Random;
  import java.io.FileWriter;
  import java.io.IOException;

  
  class MatMul {

    public static void main(String[] args) {
      int n = 600;
      int m = 100;
      int rep = 10;


      int[][] matA = new int[n][m];
      int[][] matB = new int[m][n];
      int[][] result = new int[n][n];
    

      //Llenar matrices
      fillMatrix(matA, n, m);
      fillMatrix(matB, m, n);

       //matrix multiplication repetitions
      double average = multAverage(matA, matB, result, n, m, rep);
      System.out.println("Promedio por iteración será: " + average + " segundos");

      try {
          FileWriter fileAvr = new FileWriter("java_average.txt");
          fileAvr.write(Double.toString(average));
          fileAvr.close();
      }
      catch (IOException e) {
          e.printStackTrace();
      }

    }


    static double multAverage(int[][] matA, int[][] matB, int[][] result, int n, int m, int rep){
      long average = 0;

      for(int i=0; i<rep; i++){
        long start = System.currentTimeMillis();
        matMultiplication(matA, matB, result, n, m);
    
    long end = System.currentTimeMillis();


        long execution = end - start;
        average += execution;
        System.out.println("Intento " + (i+1) + " -> " + ((double)execution/1000) + " segundos");
      }

      average = average/rep; //in milliseconds
      double avr = (double)average/1000;

      return avr;
    }

    static void matMultiplication(int[][] matA, int[][] matB, int[][] result, int n, int m){
    

      for(int i=0; i<n; i++){
        for(int j=0; j<n; j++){
          for(int k=0; k<m; k++){
            result[i][j] += matA[i][k] * matB[k][j];
          }
        }
      }
    }

    static void fillMatrix(int[][] mat, int n, int m){

      Random random = new Random();

      for (int i = 0; i < n; i++) {
        for (int j = 0; j < m; j++) {
          mat[i][j] = random.nextInt(10000);
        }
      }
    }
  }



Overwriting MatMul.java


**My own example 26 - Running the Java program that mutiplies 10 times A(600x100) and  B (100x600) matrices**

In [ ]:
!javac MatMul.java
!java MatMul

Intento 1 -> 0.118 segundos
Intento 2 -> 0.09 segundos
Intento 3 -> 0.047 segundos
Intento 4 -> 0.087 segundos
Intento 5 -> 0.083 segundos
Intento 6 -> 0.081 segundos
Intento 7 -> 0.08 segundos
Intento 8 -> 0.079 segundos
Intento 9 -> 0.096 segundos
Intento 10 -> 0.047 segundos
Promedio por iteración será: 0.08 segundos


**My own example 27 - Adding Java average execution time to the data frame**

In [ ]:
java_prom = open('java_average.txt','r')
prom_j = float(java_prom.readline())
df=app_df(df,"Java",prom_j)
df

Lenguaje  Prom. Tiempo
0         Python     11.224973
0          NumPy      0.003169
0  Fortran Magic      0.058299
0        Fortran      0.245315
0              c      0.204932
0            C++      0.308777
0           Java      0.080000

**My own example 28 - Creating a Javascript program that mutiplies 10 times A(600x100) and  B (100x600) matrices**

In [ ]:
%%writefile matMul.js
  

  function multiplyMatrices(A, B) {
    var result = new Array(A.length);
    for (var i = 0; i < A.length; i++) {
      result[i] = new Array(B[0].length);
      for (var j = 0; j < B[0].length; j++) {
        var sum = 0;
        for (var k = 0; k < B.length; k++) {
          sum += A[i][k] * B[k][j];
        }
        result[i][j] = sum;
      }
    }
    return result;
  }

  // Generate random matrices A and B
  var A = new Array(600);
  for (var i = 0; i < 600; i++) {
    A[i] = new Array(100);
    for (var j = 0; j < 100; j++) {
      A[i][j] = Math.floor(Math.random() * 10);
    }
  }

  var B = new Array(100);
  for (var i = 0; i < 100; i++) {
    B[i] = new Array(600);
    for (var j = 0; j < 600; j++) {
      B[i][j] = Math.floor(Math.random() * 10);
    }
  }

  // Multiply matrices A and B
  var C = multiplyMatrices(A, B);

  console.log(C);

Writing matMul.js


**My own example 29 - Running the Javascript program that mutiplies 10 times A(600x100) and  B (100x600) matrices**

In [ ]:
!node matMul.js

[
  [
    1798, 1781, 1859, 1647, 1641, 1928, 1570, 1596, 1850, 1685,
    1573, 1886, 1972, 1487, 1932, 2077, 1779, 1752, 1902, 1945,
    2050, 1806, 1757, 1795, 1959, 2301, 1834, 1755, 1704, 1726,
    1798, 1896, 1922, 2237, 2002, 1751, 1727, 1898, 1998, 1896,
    2103, 1847, 1940, 1930, 1862, 2146, 2229, 1979, 2108, 2169,
    1870, 1894, 1887, 1674, 2142, 1662, 1948, 1967, 1842, 2076,
    1958, 2001, 1731, 1762, 1893, 1757, 1882, 2202, 1826, 1987,
    1924, 1652, 1970, 1881, 1960, 1839, 1976, 1623, 1949, 1910,
    1746, 1905, 2296, 2008, 2136, 1877, 2184, 2081, 1998, 1778,
    1819, 1754, 1831, 1993, 1817, 1615, 1691, 1630, 1775, 2061,
    ... 500 more items
  ],
  [
    1937, 1819, 1926, 1940, 1632, 1990, 1886, 1709, 1833, 1806,
    1786, 1812, 2063, 1766, 1936, 2111, 1811, 1724, 2044, 2088,
    1947, 1909, 1816, 1918, 2064, 2186, 1986, 1806, 2045, 1806,
    2013, 1905, 2012, 2104, 2017, 1846, 1961, 2046, 1928, 1883,
    2067, 1964, 1903, 2023, 1817, 1982, 2149, 1850, 2165, 2127,
  

**My own example 30 - Adding Javascript average execution time to the data frame**

In [ ]:
list4=[]
def tiempo():
  for i in range(1):
    inicio=time.time()

    !node matMul.js
    
    final=time.time()

    list4.append(final-inicio)

  return list4
tiempo()
print("El tiempo promedio por multipicación es {0}".format(np.mean(list4)/10))
prom_jc=np.mean(list4)/10
df=app_df(df,"Javascript",prom_jc)
df

[
  [
    2088, 2130, 2141, 2041, 2089, 1966, 1815, 2305, 2021, 2319,
    1771, 2183, 1968, 1965, 2031, 2122, 1857, 2295, 2097, 2260,
    2099, 2299, 2020, 2192, 2187, 2222, 2146, 2069, 2172, 1832,
    2162, 1803, 1994, 1867, 2112, 1842, 1933, 2219, 2111, 2225,
    1825, 1926, 2300, 2142, 1933, 2368, 2109, 2036, 1941, 2234,
    1923, 2100, 2018, 1933, 2129, 2205, 1977, 2105, 1979, 1981,
    2122, 2076, 1979, 1882, 2033, 1870, 2184, 2095, 2219, 2150,
    2256, 1890, 2050, 2090, 1797, 2223, 2228, 1820, 2253, 2112,
    2064, 2081, 2144, 2236, 1899, 1803, 2205, 1881, 1907, 1938,
    2019, 2127, 1891, 1775, 2158, 1861, 2077, 1916, 1964, 1891,
    ... 500 more items
  ],
  [
    2049, 2196, 2113, 2162, 1972, 2005, 2008, 2298, 2118, 2279,
    1925, 2107, 2136, 1851, 2066, 2212, 1969, 2195, 2194, 2222,
    2080, 2354, 2211, 2093, 2235, 2254, 2043, 2027, 2139, 1885,
    2435, 1918, 2104, 1982, 2241, 1985, 2108, 2254, 1949, 2192,
    1929, 1824, 2424, 2226, 2007, 2373, 2060, 1855, 1849, 2180,
  

Lenguaje  Prom. Tiempo
0         Python     11.224973
0          NumPy      0.003169
0  Fortran Magic      0.058299
0        Fortran      0.245315
0              c      0.204932
0            C++      0.308777
0           Java      0.080000
0     Javascript      0.044067

**My own example 31 - Finding the minimun average esecuiton time in the data frame**

In [ ]:
prom_min=np.min(df["Prom. Tiempo"])
prom_min

0.003169131278991699

**My own example 32 - Adding the Speed factor columne to the data frame**

In [ ]:
#Se debe crear una nueva columna en el DF
vel=[]
vel=df["Prom. Tiempo"]/prom_min
df["Factor Vel"]=vel

Lenguaje  Prom. Tiempo   Factor Vel
0         Python     11.224973  3541.971660
0          NumPy      0.003169     1.000000
0  Fortran Magic      0.058299    18.395913
0        Fortran      0.245315    77.407710
0              c      0.204932    64.665182
0            C++      0.308777    97.432695
0           Java      0.080000    25.243511
0     Javascript      0.044067    13.905050

**My own example 33 - Sorting the the data frame by average execution time**

In [ ]:
#Organizar el dataframe por tiempo promedio de ejecución
df.sort_values(by="Prom. Tiempo")

Lenguaje  Prom. Tiempo   Factor Vel
0          NumPy      0.003169     1.000000
0     Javascript      0.044067    13.905050
0  Fortran Magic      0.058299    18.395913
0           Java      0.080000    25.243511
0              c      0.204932    64.665182
0        Fortran      0.245315    77.407710
0            C++      0.308777    97.432695
0         Python     11.224973  3541.971660

## Why is the Python Version so Much Slower?

In [ ]:
# Dynamic typing.
def mul_elemwise(xs, ys):
    return [x * y for x, y in zip(xs, ys)]

mul_elemwise([1, 2, 3, 4], [1, 2 + 0j, 3.0, 'four'])
#[type(x) for x in _]

[1, (4+0j), 9.0, 'fourfourfourfour']

In [ ]:
# Interpretation overhead.
source_code = 'a + b * c'
bytecode = compile(source_code, '', 'eval')
import dis; dis.dis(bytecode)

  1           0 LOAD_NAME                0 (a)
              2 LOAD_NAME                1 (b)
              4 LOAD_NAME                2 (c)
              6 BINARY_MULTIPLY
              8 BINARY_ADD
             10 RETURN_VALUE


## Why is the Python Version so Slow?
- Dynamic typing means that every single operation requires dispatching on the input type.
- Having an interpreter means that every instruction is fetched and dispatched at runtime.
- Other overheads:
  - Arbitrary-size integers.
  - Reference-counted garbage collection.

> This is the paradox that we have to work with when we're doing scientific or numerically-intensive Python. What makes Python fast for development -- this high-level, interpreted, and dynamically-typed aspect of the language -- is exactly what makes it slow for code execution.

- Jake VanderPlas, [*Losing Your Loops: Fast Numerical Computing with NumPy*](https://www.youtube.com/watch?v=EEUXKG97YRw)

# What Do We Do?

<center><img src="https://raw.githubusercontent.com/ssanderson/pydata-toolbox/master/notebooks/images/runaway.gif" alt="Drawing" style="width: 50%;"/></center>

<center><img src="https://raw.githubusercontent.com/ssanderson/pydata-toolbox/master/notebooks/images/thisisfine.gif" alt="Drawing" style="width: 1080px;"/></center>

- Python is slow for numerical computation because it performs dynamic dispatch on every operation we perform...

- ...but often, we just want to do the same thing over and over in a loop!

- If we don't need Python's dynamicism, we don't want to pay (much) for it.

- **Idea:** Dispatch **once per operation** instead of **once per element**.

In [ ]:
import numpy as np

data = np.array([1, 2, 3, 4])
data

array([1, 2, 3, 4])

In [ ]:
data + data

array([2, 4, 6, 8])

In [ ]:
%%time
# Naive dot product
(array_data * array_data).sum()

CPU times: user 1.2 ms, sys: 4 µs, total: 1.2 ms
Wall time: 1.21 ms


333328333350000.0

In [ ]:
%%time
# Built-in dot product.
array_data.dot(array_data)

CPU times: user 1.35 ms, sys: 3.03 ms, total: 4.38 ms
Wall time: 6.91 ms


333328333350000.0

In [ ]:
%%time
fortran_dot_product(array_data, array_data)

CPU times: user 213 µs, sys: 0 ns, total: 213 µs
Wall time: 220 µs


333328333350000.0

In [ ]:
# Numpy won't allow us to write a string into an int array.
data[0] = "foo"

ValueError: ignored

In [ ]:
# We also can't grow an array once it's created.
data.append(3)

AttributeError: ignored

In [ ]:
# We **can** reshape an array though.
two_by_two = data.reshape(2, 2)
two_by_two

array([[1, 2],
       [3, 4]])

Numpy arrays are:

- Fixed-type

- Size-immutable

- Multi-dimensional

- Fast\*

\* If you use them correctly.

# What's in an Array?

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6], dtype='int16').reshape(2, 3)
print("Array:\n", arr, sep='')
print("===========")
print("DType:", arr.dtype)
print("Shape:", arr.shape)
print("Strides:", arr.strides)
print("Data:", arr.data.tobytes())

Array:
[[1 2 3]
 [4 5 6]]
DType: int16
Shape: (2, 3)
Strides: (6, 2)
Data: b'\x01\x00\x02\x00\x03\x00\x04\x00\x05\x00\x06\x00'


# Core Operations

- Vectorized **ufuncs** for elementwise operations.
- Fancy indexing and masking for selection and filtering.
- Aggregations across axes.
- Broadcasting

# UFuncs

UFuncs (universal functions) are functions that operate elementwise on one or more arrays.

In [ ]:
data = np.arange(15).reshape(3, 5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
# Binary operators.
data * data

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196]])

In [ ]:
# Unary functions.
np.sqrt(data)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739]])

In [ ]:
# Comparison operations
(data % 3) == 0

array([[ True, False, False,  True, False],
       [False,  True, False, False,  True],
       [False, False,  True, False, False]])

In [ ]:
# Boolean combinators.
((data % 2) == 0) & ((data % 3) == 0)

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False]])

In [ ]:
# as of python 3.5, @ is matrix-multiply
data @ data.T

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

# UFuncs Review

- UFuncs provide efficient elementwise operations applied across one or more arrays.
- Arithmetic Operators (`+`, `*`, `/`)
- Comparisons (`==`, `>`, `!=`)
- Boolean Operators (`&`, `|`, `^`)
- Trigonometric Functions (`sin`, `cos`)
- Transcendental Functions (`exp`, `log`)

# Selections

We often want to perform an operation on just a subset of our data.

In [ ]:
sines = np.sin(np.linspace(0, 3.14, 10))
cosines = np.cos(np.linspace(0, 3.14, 10))
sines

array([0.        , 0.34185385, 0.64251645, 0.86575984, 0.98468459,
       0.98496101, 0.8665558 , 0.64373604, 0.34335012, 0.00159265])

In [ ]:
# Slicing works with the same semantics as Python lists.
sines[0]

0.0

In [ ]:
sines[:3]  # First three elements  

array([0.        , 0.34185385, 0.64251645])

In [ ]:
sines[5:]  # Elements from 5 on.

array([0.98496101, 0.8665558 , 0.64373604, 0.34335012, 0.00159265])

In [ ]:
sines[::2]  # Every other element.

array([0.        , 0.64251645, 0.98468459, 0.8665558 , 0.34335012])

In [ ]:
# More interesting: we can index with boolean arrays to filter by a predicate.
print("sines:\n", sines)
print("sines > 0.5:\n", sines > 0.5)
print("sines[sines > 0.5]:\n", sines[sines > 0.5])

sines:
 [0.         0.34185385 0.64251645 0.86575984 0.98468459 0.98496101
 0.8665558  0.64373604 0.34335012 0.00159265]
sines > 0.5:
 [False False  True  True  True  True  True  True False False]
sines[sines > 0.5]:
 [0.64251645 0.86575984 0.98468459 0.98496101 0.8665558  0.64373604]


In [ ]:
# We index with lists/arrays of integers to select values at those indices.
print(sines)
sines[[0, 4, 7]]

[0.         0.34185385 0.64251645 0.86575984 0.98468459 0.98496101
 0.8665558  0.64373604 0.34335012 0.00159265]


array([0.        , 0.98468459, 0.64373604])

In [ ]:
# Index arrays are often used for sorting one or more arrays.
unsorted_data = np.array([1, 3, 2, 12, -1, 5, 2])

In [ ]:
sort_indices = np.argsort(unsorted_data)
sort_indices

array([4, 0, 2, 6, 1, 5, 3])

In [ ]:
unsorted_data[sort_indices]

array([-1,  1,  2,  2,  3,  5, 12])

In [ ]:
market_caps = np.array([12, 6, 10, 5, 6])  # Presumably in dollars?
assets = np.array(['A', 'B', 'C', 'D', 'E'])

In [ ]:
# Sort assets by market cap by using the permutation that would sort market caps on ``assets``.
sort_by_mcap = np.argsort(market_caps)
assets[sort_by_mcap]

array(['D', 'B', 'E', 'C', 'A'], dtype='<U1')

In [ ]:
# Indexers are also useful for aligning data.
print("Dates:\n", repr(event_dates))
print("Values:\n", repr(event_values))
print("Calendar:\n", repr(calendar))

Dates:
 array(['2017-01-06', '2017-01-07', '2017-01-08'], dtype='datetime64[D]')
Values:
 array([10, 15, 20])
Calendar:
 array(['2017-01-03', '2017-01-04', '2017-01-05', '2017-01-06',
       '2017-01-09', '2017-01-10', '2017-01-11', '2017-01-12',
       '2017-01-13', '2017-01-17', '2017-01-18', '2017-01-19',
       '2017-01-20', '2017-01-23', '2017-01-24', '2017-01-25',
       '2017-01-26', '2017-01-27', '2017-01-30', '2017-01-31',
       '2017-02-01'], dtype='datetime64[D]')


In [ ]:
print("Raw Dates:", event_dates)
print("Indices:", calendar.searchsorted(event_dates))
print("Forward-Filled Dates:", calendar[calendar.searchsorted(event_dates)])

Raw Dates: ['2017-01-06' '2017-01-07' '2017-01-08']
Indices: [3 4 4]
Forward-Filled Dates: ['2017-01-06' '2017-01-09' '2017-01-09']


On multi-dimensional arrays, we can slice along each axis independently.

In [ ]:
data = np.arange(25).reshape(5, 5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
data[:2, :2]  # First two rows and first two columns.

array([[0, 1],
       [5, 6]])

In [ ]:
data[:2, [0, -1]]  # First two rows, first and last columns.

array([[0, 4],
       [5, 9]])

In [ ]:
data[(data[:, 0] % 2) == 0]  # Rows where the first column is divisible by two.

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

# Selections Review

- Indexing with an integer removes a dimension.
- Slicing operations work on Numpy arrays the same way they do on lists.
- Indexing with a boolean array filters to True locations.
- Indexing with an integer array selects indices along an axis.
- Multidimensional arrays can apply selections independently along different axes.

## Reductions

Functions that reduce an array to a scalar.

$Var(X) = \frac{1}{N}\sqrt{\sum_{i=1}^N (x_i - \bar{x})^2}$

In [ ]:
def variance(x):
    return ((x - x.mean()) ** 2).sum() / len(x)

In [ ]:
variance(np.random.standard_normal(1000))

0.9575980702269989

- `sum()` and `mean()` are both **reductions**.

- In the simplest case, we use these to reduce an entire array into a single value...

In [ ]:
data = np.arange(30)
data.mean()

14.5

- ...but we can do more interesting things with multi-dimensional arrays.

In [ ]:
data = np.arange(30).reshape(3, 10)
data

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [ ]:
data.mean()

14.5

In [ ]:
data.mean(axis=0)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19.])

In [ ]:
data.mean(axis=1)

array([ 4.5, 14.5, 24.5])

## Reductions Review

- Reductions allow us to perform efficient aggregations over arrays.
- We can do aggregations over a single axis to collapse a single dimension.
- Many built-in reductions (`mean`, `sum`, `min`, `max`, `median`, ...).

# Broadcasting

In [ ]:
row = np.array([1, 2, 3, 4])
column = np.array([[1], [2], [3]])
print("Row:\n", row, sep='')
print("Column:\n", column, sep='')

Row:
[1 2 3 4]
Column:
[[1]
 [2]
 [3]]


In [ ]:
row + column

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

<center><img src="https://raw.githubusercontent.com/ssanderson/pydata-toolbox/master/notebooks/images/broadcasting.png" alt="Drawing" style="width: 60%;"/></center>

<h5>Source: http://www.scipy-lectures.org/_images/numpy_broadcasting.png</h5>

In [ ]:
# Broadcasting is particularly useful in conjunction with reductions.
print("Data:\n", data, sep='')
print("Mean:\n", data.mean(axis=0), sep='')
print("Data - Mean:\n", data - data.mean(axis=0), sep='')

Data:
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
Mean:
[10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
Data - Mean:
[[-10. -10. -10. -10. -10. -10. -10. -10. -10. -10.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [ 10.  10.  10.  10.  10.  10.  10.  10.  10.  10.]]


# Broadcasting Review

- Numpy operations can work on arrays of different dimensions as long as the arrays' shapes are still "compatible".
- Broadcasting works by "tiling" the smaller array along the missing dimension.
- The result of a broadcasted operation is always at least as large in each dimension as the largest array in that dimension.

# Numpy Review

- Numerical algorithms are slow in pure Python because the overhead dynamic dispatch dominates our runtime.

- Numpy solves this problem by:
  1. Imposing additional restrictions on the contents of arrays.
  2. Moving the inner loops of our algorithms into compiled C code.

- Using Numpy effectively often requires reworking an algorithms to use vectorized operations instead of for-loops, but the resulting operations are usually simpler, clearer, and faster than the pure Python equivalent.

<center><img src="https://raw.githubusercontent.com/ssanderson/pydata-toolbox/master/notebooks/images/unicorn.jpg" alt="Drawing" style="width: 75%;"/></center>

Numpy is great for many things, but...

- Sometimes our data is equipped with a natural set of **labels**:
  - Dates/Times
  - Stock Tickers
  - Field Names (e.g. Open/High/Low/Close)

- Sometimes we have **more than one type of data** that we want to keep grouped together.
  - Tables with a mix of real-valued and categorical data.

- Sometimes we have **missing** data, which we need to ignore, fill, or otherwise work around.

<center><img src="https://raw.githubusercontent.com/ssanderson/pydata-toolbox/master/notebooks/images/panda-wrangling.gif" alt="Drawing" style="width: 75%;"/></center>

<center><img src="https://raw.githubusercontent.com/ssanderson/pydata-toolbox/master/notebooks/images/pandas_logo.png" alt="Drawing" style="width: 75%;"/></center>


Pandas extends Numpy with more complex data structures:

- `Series`: 1-dimensional, homogenously-typed, labelled array.
- `DataFrame`: 2-dimensional, semi-homogenous, labelled table.

Pandas also provides many utilities for: 
- Input/Output
- Data Cleaning
- Rolling Algorithms
- Plotting

# Selection in Pandas

In [ ]:
s = pd.Series(index=['a', 'b', 'c', 'd', 'e'], data=[1, 2, 3, 4, 5])
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [ ]:
# There are two pieces to a Series: the index and the values.
print("The index is:", s.index)
print("The values are:", s.values)

The index is: Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
The values are: [1 2 3 4 5]


In [ ]:
# We can look up values out of a Series by position...
s.iloc[0]

1

In [ ]:
# ... or by label.
s.loc['a']

1

In [ ]:
# Slicing works as expected...
s.iloc[:2]

a    1
b    2
dtype: int64

In [ ]:
# ...but it works with labels too!
s.loc[:'c']

a    1
b    2
c    3
dtype: int64

In [ ]:
# Fancy indexing works the same as in numpy.
s.iloc[[0, -1]]

a    1
e    5
dtype: int64

In [ ]:
# As does boolean masking.
s.loc[s > 2]

c    3
d    4
e    5
dtype: int64

In [ ]:
# Element-wise operations are aligned by index.
other_s = pd.Series({'a': 10.0, 'c': 20.0, 'd': 30.0, 'z': 40.0})
other_s

a    10.0
c    20.0
d    30.0
z    40.0
dtype: float64

In [ ]:
s + other_s

a    11.0
b     NaN
c    23.0
d    34.0
e     NaN
z     NaN
dtype: float64

In [ ]:
# We can fill in missing values with fillna().
(s + other_s).fillna(0.0)

a    11.0
b     0.0
c    23.0
d    34.0
e     0.0
z     0.0
dtype: float64

In [ ]:
# Most real datasets are read in from an external file format.
aapl = pd.read_csv('AAPL.csv', parse_dates=['Date'], index_col='Date')
aapl.head()

FileNotFoundError: ignored

In [ ]:
# Slicing generalizes to two dimensions as you'd expect:
aapl.iloc[:2, :2]

In [ ]:
aapl.loc[pd.Timestamp('2010-02-01'):pd.Timestamp('2010-02-04'), ['Close', 'Volume']]

# Rolling Operations

<center><img src="https://raw.githubusercontent.com/ssanderson/pydata-toolbox/master/notebooks/images/rolling.gif" alt="Drawing" style="width: 75%;"/></center>

In [ ]:
aapl.rolling(5)[['Close', 'Adj Close']].mean().plot();

In [ ]:
# Drop `Volume`, since it's way bigger than everything else.
aapl.drop('Volume', axis=1).resample('2W').max().plot();

In [ ]:
# 30-day rolling exponentially-weighted stddev of returns.
aapl['Close'].pct_change().ewm(span=30).std().plot();

# "Real World" Data

In [ ]:
from demos.avocados import read_avocadata

avocados = read_avocadata('2014', '2016')
avocados.head()

In [ ]:
# Unlike numpy arrays, pandas DataFrames can have a different dtype for each column.
avocados.dtypes

In [ ]:
# What's the regional average price of a HASS avocado every day?
hass = avocados[avocados.Variety == 'HASS']
hass.groupby(['Date', 'Region'])['Weighted Avg Price'].mean().unstack().ffill().plot();

In [ ]:
def _organic_spread(group):

    if len(group.columns) != 2:
        return pd.Series(index=group.index, data=0.0)
    
    is_organic = group.columns.get_level_values('Organic').values.astype(bool)
    organics = group.loc[:, is_organic].squeeze()
    non_organics = group.loc[:, ~is_organic].squeeze()
    diff = organics - non_organics
    return diff

def organic_spread_by_region(df):
    """What's the difference between the price of an organic 
    and non-organic avocado within each region?
    """
    return (
        df
        .set_index(['Date', 'Region', 'Organic'])
         ['Weighted Avg Price']
        .unstack(level=['Region', 'Organic'])
        .ffill()
        .groupby(level='Region', axis=1)
        .apply(_organic_spread)
    )

In [ ]:
organic_spread_by_region(hass).plot();
plt.gca().set_title("Daily Regional Organic Spread");
plt.legend(bbox_to_anchor=(1, 1));

In [ ]:
spread_correlation = organic_spread_by_region(hass).corr()
spread_correlation

In [ ]:
import seaborn as sns
grid = sns.clustermap(spread_correlation, annot=True)
fig = grid.fig
axes = fig.axes
ax = axes[2]
ax.set_xticklabels(ax.get_xticklabels(), rotation=45);

# Pandas Review

- Pandas extends numpy with more complex datastructures and algorithms.
- If you understand numpy, you understand 90% of pandas.
- `groupby`, `set_index`, and `unstack` are powerful tools for working with categorical data.
- Avocado prices are surprisingly interesting :)

# Thanks!